Add Websockets for submits in problems. Related to #39
petr-kalinin/algoprog pull request #157
Opened 2020-09-05 19:25 UTC by fredeom

2020-09-06 11:12 UTC, petr-kalinin reviewed
И вдобавок к комментариям по коду -- еще надо понять, как восстанавливать вебсокет-соединение в случае если оно разорвалось. Я бы предлагал все-таки посмотреть в сторону Socket.io или других подобных библиотек, которые сами умеют переустанавливать соединение.

2020-09-06 11:12 UTC, petr-kalinin commented on client/components/SubmitList.coffee
>              if props?.findMistake
Для findMistake тоже вебсокеты полезны, их тоже лучше заодно перенести.

2020-09-06 11:12 UTC, petr-kalinin commented on client/components/SubmitList.coffee
>      timeout: 20 * 1000
Кажется, timeout тогда уже можно убрать

2020-09-06 11:12 UTC, petr-kalinin commented on client/lib/ConnectedComponent.coffee
> +export WsConnectedComponent = (Component, options) ->
У WsConnectedComponent 99% кода дублируется с ConnectedComponent. Думаю, не надо делать новый компонент, надо просто к ConnectedComponents добавить работу в сокетами. Например, сделав в options рядом с urls параметр wsurls.

2020-09-06 11:12 UTC, petr-kalinin commented on server/api/setupApi.coffee
> +getRandomString = (length) =>
Странно, неужели нет способа сделать это проще. Как минимум, есть вот такой хак: https://gist.github.com/6174/6062387

2020-09-06 11:12 UTC, petr-kalinin commented on server/api/setupApi.coffee
> +        addCallback 'update_submit', getRandomString(5), ->
Возвращаемое значение getRandomString нигде тут не используется. Поэтому вообще непонятно, зачем setupApi знать про это randomString. Пусть addCallback внутри себя генерирует случайную строку, если уж ему так надо.

2020-09-06 11:12 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +export addCallback = (schemeName, cbName, cb) ->
Слишком общие названия, в setupApi очень плохо смотрится вызов addCallback. Лучше addMongooseCallback. И аналогично тогда уж с addHook

2020-09-06 11:12 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +scheme2cb = {}
MongooseCallbackManager — это не модель, ему нечего делать в server/models. Лучше положить в server/mongo

2020-09-06 11:12 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +export addHook = (schemeName) ->
Здесь сейчас получается, что после обновления _любого_ результата будут вызваны _все_ установленные коллбеки и по всем существующим сокетам будут отправлены данные. Хотя на самом деле надо отправлять только тому пользователю, у коорого обновился результат. Я предлагаю в addCallback передавать id пользователя, чьи результаты нам интересны (благо сейчас все сокеты работают с конкретным пользователем), в scheme2cb сделать еще один уровень по пользователям (типа scheme2cb[schemeName][userId][cbName], и в хуке узнавать id пользователя, чей результат изменился, и вызывать только его коллбеки.

2020-09-06 11:15 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +scheme2cb = {}
И еще давай сразу добавим метрику на количество активных соединений, чтобы в sendMetrics оно отправлялось в графит.

2020-09-06 11:15 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +            catch e
По сути, мы удаляем объект сокета тут только после неудачной отправки данных. Но если пользователь сдавал задачи, все насдавал, закрыл браузер и ушел, то возможно у нас не будет новых данных, которые ему надо отправить (ведь он ничего больше не сдает), и тогда на стороне сервера соединение будет висеть, и такие соединения будут копиться. Надо бы что-то придумать против этого; собственно, тот же Socket.io, как я понимаю, умеет оперативно детектировать разрыв соединения.

2020-09-06 14:06 UTC, fredeom commented on server/models/MongooseCallbackManager.coffee
> +export addHook = (schemeName) ->
Можно ли везде, где мы хуки применяем в upsert заменить update на updateOne?
Дело в том, что в хуке на updateOne возвращается документ из которого можно понять пользователя, а вот из update хуков возвращается какая-то фигня.

![image](https://user-images.githubusercontent.com/2552868/92327541-18fec600-f063-11ea-827b-5f6111d88e5a.png)

2020-09-06 15:06 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +export addHook = (schemeName) ->
Посмотри по смыслу кода. Скорее всего да, можно везде updateOne, главное чтобы он поддерживал upsert.

2020-09-06 15:11 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +export addHook = (schemeName) ->
Кстати, я тут подумал -- у нас же на самом деле из основного кода по идее не должны вызываться напрямую монго-методы, должны вызываться только методы, определенные в схеме. А тогда на самом деле и хуков не надо, можно прямо из upsert дергать mongooseConnectionManager. И заодно не надо будет думать про то, какие именно методы вызываются, и т.д.

2020-09-07 07:54 UTC, fredeom commented on server/models/MongooseCallbackManager.coffee
> +scheme2cb = {}
Не понял. В MongooseCallbackManager находится информация о количестве активных соединений, но в графит её должен передавать sendMetrics? Т.е. нужно создать модель, в которой хранить количество активных соединений и в sendGraphite или подобной функции их отсылать, либо отсылать в графит напрямую из MongooseCallbackManager-а?

2020-09-07 08:13 UTC, fredeom commented on server/models/MongooseCallbackManager.coffee
> +            catch e
> тот же Socket.io, как я понимаю, умеет оперативно детектировать разрыв соединения.

ws.on 'close', ()->
   console.log 'Обыкновенный сокет тоже может детектировать закрытие'

Я кстати думал о том, что рандомная страка мне нужна именно в вебсокетной ручке, чтобы во время детекции закрытия сокета дёргать метод по его удалению из scheme2cb

2020-09-07 08:17 UTC, fredeom commented on server/models/MongooseCallbackManager.coffee
> +            catch e
Ещё проще: передавать ws из ручки в метод addMongooseCallback и в нём на onclose вешать удаление из scheme2cb

2020-09-07 08:38 UTC, fredeom commented on server/models/MongooseCallbackManager.coffee
> +scheme2cb = {}
Надо переделать функцию sendGraphite, либо отдельную создать?
Подсчитывать сумарное количество колбеков, либо разделить по пользователям?
С каким ключём класть количество колбеков в "metrics = {}"

2020-09-07 08:50 UTC, petr-kalinin commented on server/models/MongooseCallbackManager.coffee
> +scheme2cb = {}
Я думаю сделать отдельную функцию. Разбивать по пользователям не надо. Ключ -- "websockets"

2020-09-11 17:48 UTC, petr-kalinin requested changes
В целом да, все очень неплохо работает и выглядит круто. Но пофикси комментарии.

2020-09-11 17:48 UTC, petr-kalinin commented on client/components/SubmitList.coffee
> +            #if props?.findMistake
Комментарии, конечно, надо убрать

2020-09-11 17:48 UTC, petr-kalinin commented on server/mongo/MongooseCallbackManager.coffee
> +    for k of scheme2cb?[schemeName]?[user]
Ты, кстати, проверял, работает ли это, если `scheme2cb?[schemeName]?[user] == undefined` (т.е. этот пользователь сейчас не подключен)? Мне кажется, итерация сломается. Надо написать типа
`for k of scheme2cb?[schemeName]?[user] || {}`

2020-09-11 17:48 UTC, petr-kalinin commented on client/lib/callApi.coffee
> +        ws = new WebSocket(WS_API_URL + endpoint)
Надо бы все-таки уметь переподключать сокет при разрыве соединения. Например, я вот с ходу нагуглил еще такую штуку: https://www.npmjs.com/package/reconnecting-websocket , см. еще https://stackoverflow.com/a/48217905/3216312 . Ну или банально вручную сделать, примерно по такому образцу: https://www.tutorialspoint.com/How-to-reconnect-to-websocket-after-close-connection-with-HTML

2020-09-11 17:48 UTC, petr-kalinin commented on server/server.coffee
> +expressWs = require('express-ws')(app)
Не находит модуль. Ты, похоже, забыл написать `npm install --save`

2020-09-11 17:48 UTC, petr-kalinin commented on server/mongo/MongooseCallbackManager.coffee
> +    for k of scheme2cb?[schemeName]?[user]
Хотя я потестил, вроде и так работает.

2020-09-11 19:01 UTC, fredeom commented on server/mongo/MongooseCallbackManager.coffee
> +    for k of scheme2cb?[schemeName]?[user]
Это фишка кофе: не запускать циклы, когда итерируемый обьект возвращает undefined

2020-09-12 18:49 UTC, petr-kalinin requested changes

2020-09-12 18:49 UTC, petr-kalinin commented on client/lib/callApi.coffee
> +    if window?
Я понял еще одну большую проблему. На клиентской стороне вебсокеты никогда не удаляются. Пока страничка открыта в браузере, они будут копиться. Даже если пользователь перейдет в другую задачу, вебсокеты по старой задаче останутся открытыми.

Надо видимо в ConnectedComponent обрабатывать типа componentWillUnmount и componentWillUpdate, и как-то уметь оттуда достучаться до объектов вебсокетов. Видимо, для этого надо сохранять вебсокет в redux state, и сделать новую action чтобы вебсокет закрыть.

2020-09-16 14:46 UTC, petr-kalinin commented on client/lib/callApi.coffee
> +            ws.onclose = wsCloseListener
Кстати, еще. Переустанавливать соединение надо конечно не мгновенно, а то в случае проблем с сервером или с интернетом будет слишком много перезапросов. Вообще в идеале нужно экспоненциальное увеличение таймаута с увеличением номера попытки, но можно для простоты просто поставить задержку типа 20 секунд, например.

2020-09-18 18:00 UTC, petr-kalinin requested changes

2020-09-18 18:00 UTC, petr-kalinin commented on server/mongo/MongooseCallbackManager.coffee
> +            delete scheme2cb[schemeName][user][k]
Кстати, интересно, а так можно? Тут не случится какой-нибудь инвалидации итераторов из-за того, что мы тут итерируемся по k?

2020-09-19 06:59 UTC, fredeom commented on client/components/Level.coffee
> +    <div className={if props.className then styles[props.className]}>
className={false} возвращает ворнинг, правильно будет className={условие ? значение : undefined} или как я написал, если это кофе скрипт.

2020-09-19 07:06 UTC, fredeom commented on client/lib/Memento.coffee
> +memento = {};
Потому, что он не обязательно относится к вебсокетам. Он для условной строки хранит единицу и удаляет эту единицу когда подписка на эту условную строку заканчивается. То есть его можно использовать в разных местах, а как назвать я не знаю.

2020-09-19 07:10 UTC, fredeom commented on client/lib/callApi.coffee
> +            timeout = setInterval ->
Каждые 5 сек выполняется проверка на наличие в словаре условной строки. Это очень дёшево.
В альтернативном случае мы должны каждый раз при отсоединении класть в словарь новый сокет, это сложнее.

2020-09-19 07:48 UTC, fredeom commented on server/mongo/MongooseCallbackManager.coffee
> +            delete scheme2cb[schemeName][user][k]
Аналогичный цикл в js проходит без проблем, да и ошибок на инвалидацию при тестировании я не обнаруживал.

![изображение](https://user-images.githubusercontent.com/2552868/93662046-8f3cf880-fa65-11ea-807a-024222f0eaa9.png)

2020-09-19 08:32 UTC, petr-kalinin commented on server/mongo/MongooseCallbackManager.coffee
> +            delete scheme2cb[schemeName][user][k]
Ок, хорошо

2020-09-19 08:35 UTC, petr-kalinin commented on client/components/Level.coffee
> +    <div className={if props.className then styles[props.className]}>
Ок, ладно, хотя лучше было бы это отдельным ПРом сделать

2020-09-19 08:44 UTC, petr-kalinin commented on client/lib/Memento.coffee
> +memento = {};
Смотри. Тут два соображения.

Во-первых, я последнее время прихожу к выводу, что даже если класс сам по себе достаточно общий, но используется только в одном конкретном контексте, то лучше назвать его по использованию, а не по тому, что он из себя представляет. Условно говоря, если у тебя есть планировщик задач и в нем очередь задач, которая является обычной очередью с приоритетами, то все равно ее лучше назвать TaskPriorityQueue, хотя возможно внутри себя она ничено не знает про то, что она работает с тасками. Потому что так намного понятнее при чтении кода — при чтении этого класса сразу понятно, зачем этот класс используется, при чтении места, где он используется, тоже сразу понятнее, что происходит. Вот когда уже у класса возникают применения в совсем разных местах, тогда да, надо придумать общее название, но тогда почти наверняка его еще и потребуется как-то дорабатывать, делать более общим и т.п., потому что очень редко бывает так, что класс, сделанный изначально для одного применения, можно сразу использовать и в других местах.

Во-вторых, здесь у тебя даже не класс, здесь у тебя по сути глобальная переменная. Ее как она есть сейчас невозможно использовать в разных местах, потому что объект один и, например, начнутся конфликты по строкам (если разные использования будут использовать одни и те же строки-ключи), да и вообще будет очень странно выглядеть, если из совсем разных частей кода идет обращение к одной переменной в совсем разных целях. Поэтому если действительно закладываться на общее использование, то надо сделать отдельный _класс_ Memento (и тогда сразу понятно, как его назвать -- конечно, не Memento, а банально Set, потому что это просто множество строк) и несколько инстансов для каждого применения, ну и тогда совершенно естественным образом у тебя будет переменная websocketsMemento (websocketsSet), т.е. слово websockets все равно вылезает. Но опять-таки, если это пока единственное применение, то зачем делать отдельный класс, почему бы просто не сделать глобальную переменную websocketsMemento (websocketsSet)? А класс можно будет сделать потом, если действительно понадобится несколько применений, но тогда скорее всего понадобятся еще доработки, поэтому заранее делать класс не имеет особого смысла. (А на самом деле я скорее думаю, что этот код будет эволюционировать не в сторону общего компонента для разных целей, а в сторону именно менеджера вебсокетов, потому что, как я уже писал, для перевода других ручек на вебсокеты понадобится единое место хранения всех имеющихся вебсокетов.)

2020-09-19 08:46 UTC, petr-kalinin commented on client/lib/callApi.coffee
> +            timeout = setInterval ->
Ну ладно, ок, с учетом того, что для масштабного применения вебсокетов (п. 2 основного тикета) все равно придется тут довольно много рефакторить.

2020-09-19 09:57 UTC, fredeom commented on server/api/setupApi.coffee
> +            if ws?.readyState != ws?.OPEN then return
Пока убрал эти строки потому, что глитча с ошибкой больше не повторилось

2020-09-19 19:25 UTC, petr-kalinin approved these changes

2020-09-19 19:25 UTC, merged