Add decision comment alert(issue #125)
petr-kalinin/algoprog pull request #260
Opened 2022-07-28 15:34 UTC by UlinEgor

2022-08-01 16:26 UTC, petr-kalinin requested changes

2022-08-01 16:26 UTC, petr-kalinin commented on server/lib/telegramBot.coffee
> +export notifyUser = (id, message) ->
Сюда надо передавать id юзера на алгопроге, а не id в телеграмме. И тут делать findByIdWithTelegram и проверять наличие телеграмма.

Потому что представь себе, что из других мест в коде тоже захочется отправлять сообщения пользователям. Не хочется же каждый раз во всяком другом месте писать findByIdWithTelegram

2022-08-01 16:26 UTC, petr-kalinin commented on server/api/setOutcome.coffee
> +    return msg
Надо тут добавить ссылку на задачу, чтобы из чата пользователь мог сразу перейти к задаче.
Можно просто ссылкой в конце сообщения, можно заморочиться с html-разметкой и сделать так, чтобы название задачи было ссылкой на задачу

2022-08-01 16:26 UTC, petr-kalinin commented on server/api/setOutcome.coffee
>      problem = await Problem.findById(problemId)
Надо тут научиться получать английское названите задачи для англичан.
Для этого надо не Problem.findById, а Material.findById(problemId + lang)

2022-08-02 12:20 UTC, petr-kalinin requested changes

2022-08-02 12:20 UTC, petr-kalinin commented on server/api/setOutcome.coffee
> +    msg = generateMsg(lang, req.body.result, material.title, material._id)
Хорошо бы ниже, где создается SubmitComment, тоже использовать material.title. И тогда problem выше вообще не будет нужен.

2022-08-02 12:20 UTC, petr-kalinin commented on server/api/setOutcome.coffee
> -    await User.updateUser(submit.user, dirtyResults)
А куда это пропало?

2022-08-02 15:17 UTC, petr-kalinin requested changes

2022-08-02 15:17 UTC, petr-kalinin commented on server/api/setOutcome.coffee
> +    material = await Material.findById(problemId + lang)
Ты это тестил? У тебя же тут lang еще не определен. Тестируй все свои изменения, прежде чем обновлять ПР

2022-08-02 15:17 UTC, petr-kalinin commented on server/api/setOutcome.coffee
> +                problemName: material._id
Тут не _id, а title должно быть

2022-08-02 15:50 UTC, fredeom commented
Прошу прощение за бестолковое замечание.

Но надо как-то отличать трллизм от спешки от лени и прочих проявлений человеческой сущности.

  
>Вторник, 2 августа 2022, 18:18 +03:00 от Petr Kalinin ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>----------------------------------------------------------------------
>In  server/api/setOutcome.coffee :
>>  storeToDatabase = (req, res) ->
>
>     submit = await Submit.findById(req.params.submitId)
>
>     problemId = submit.problem
>
>-    problem = await Problem.findById(problemId)
>
>-    logger.info("Store to database #{req.params.submitId} #{problemId} #{problem?._id}")
>
>+    material = await Material.findById(problemId + lang)
>
>
>Ты это тестил? У тебя же тут lang еще не определен. Тестируй все свои изменения, прежде чем обновлять ПР
>----------------------------------------------------------------------
>In  server/api/setOutcome.coffee :
>> @@ -37,18 +74,22 @@ storeToDatabase = (req, res) ->
>
>                 _id: "_#{rndId}r#{req.params.submitId}"
>
>                 submit: req.params.submitId
>
>                 problemId: problemId
>
>-                problemName: problem.name
>
>+                problemName: material._id
>
>
>Тут не _id, а title должно быть
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <petr-kalinin/algoprog/pull/260/review/1058959757 @ github . com> 
 
 
--
Александр Смирнов
Отправлено из Почты  Mail.ru
 

2022-08-08 18:26 UTC, merged