Change default scrollbar
petr-kalinin/algoprog pull request #282
Opened 2023-05-15 15:52 UTC by egoros7

2023-05-15 18:19 UTC, petr-kalinin requested changes
См. коммент

2023-05-15 19:28 UTC, egoros7 commented on client/components/global.css
> +::-webkit-scrollbar {
Chromium, проверил, работает. К сожалению, стандарты W3C пока присутствует только к Firefox:
![image](https://github.com/petr-kalinin/algoprog/assets/64604791/6b50ad93-38f6-4b98-8215-766ad7e5fda5)

Поддержка `::-webkit-scrollbar` есть везде, но не в Firefox.
![image](https://github.com/petr-kalinin/algoprog/assets/64604791/0b9d3d84-fc3d-4897-beba-652f9f965abe)

Вот такой казус, без нестандартных свойств не обойтись.

Также появляется вопрос, какой же нам нужен внешний вид скроллбара?

2023-05-16 16:06 UTC, petr-kalinin commented on client/components/global.css
> +::-webkit-scrollbar {
> Мне нужно понять, что вам не понравилось в текущем варианте, но сейчас это сделать довольно проблематично )

Смотрите. Что мне не нравится в том, как оно выглядит сейчас. Мне не нравятся широкие серве полоски, а также не нравится то, что они прижаты к следующей строке таблицы, а не к той, которую они скроллят. В вашем решении оба недостатка остались, но еще и пропали стрелки, в результате чего стало совершенно неочевидно, что эта серая полоска -- это скроллбар. 

> А вообще, я хотел попробовать себя в гите и решил сделать PR по какой-нибудь мелкой задаче.

Вы меня извините, но вообще, по моим представлениям, обычно принято сначала связаться с автором проекта и уточнить, стоит ли браться за ту или иную задачу, нет ли тут каких-нибудь сложностей и т.п. Тем более когда речь про настолько маленький проект, как алгопрог — в нем issue могут быть вообще устаревшими или неактуальными.

А еще, если мы не знакомы, то, очевидно, вы не занимались на алгопроге -- а вы тогда смогли вообще поднять локальный алгопрог, создать там пользователя с нетривиальным непустым профилем, и своими глазами увидеть, в чем проблема в #190? Или вы вслепую сделали ПР?

2023-05-16 18:22 UTC, petr-kalinin commented on client/components/global.css
> +::-webkit-scrollbar {
В смысле, а как вы занимаетесь на алгопроге, если не знакомы со мной лично? Вы в ННГУ на занятиях занимаетесь? Ну так это можно сказать что знакомы :) 

Но тогда тем более стоило мне написать (ну и стоит, если хотите), для учеников алгопрога есть "стажировка" (https://algoprog.ru/material/internship), и я всегда рад видеть учеников алгопрога, желающих что-то улучшить. Но, действительно, это не настолько просто, как может показаться сразу.

2023-06-07 16:23 UTC, closed without merging