Added the page with last submits (closes #198)
petr-kalinin/algoprog pull request #290
Opened 2024-07-12 20:14 UTC by linburk

2024-07-21 16:59 UTC, petr-kalinin requested changes
Я посмотрел, вроде все работает, но надо разобраться с правами просмотра списка сабмитов.

2024-07-21 16:59 UTC, petr-kalinin commented on server/api/setupApi.coffee
> +        admin = checkAndLogAdminAction(req, VIEW_SUBMITS, user.userList)
Тут видимо надо не совсем так. Посмотреть, какие задачи человек сдавал, может любой пользователь -- например, в календаре посылки по дню отображаются всем желающим. Поэтому и тут список сабмитов надо отображать для всех желающих. Надо только проверить, что ничего секретного там не вылезает (типа исходников или тестов), но вроде не вылезает. Посмотри как сделан календарь?

2024-07-21 18:24 UTC, linburk commented on server/api/setupApi.coffee
> +        admin = checkAndLogAdminAction(req, VIEW_SUBMITS, user.userList)
Убрал проверку прав, json отдаёт такой же, как submitsbyday. Поправил отображение ссылки на userpage

2024-07-21 19:37 UTC, petr-kalinin commented
У тебя тут какие-то конфликты получились, видимо, из-за того, что я залил предыдущий ПР, а в нем были лишние коммиты

2024-08-06 09:26 UTC, merged

2024-08-06 09:35 UTC, petr-kalinin commented
Я залил ПР, еще небольшие комментарии.
Во-первых, следи за commit message'ами. Это не должно быть вида "fix", "upd" и т.п., должны быть понятные описания.
Во-вторых, если у тебя получается много мелких технических коммитов типа "Delete server/.DS_Store", то лучше править историю гита (git commit --amend, git rebase -i и т.п.). В целом, такая практика не рекомендуется, особенно если ты уже пушил коммиты на сервер, но если ты обнаружил, что ты закоммитил неаккуратно, то лучше сразу локально все поправить, чтобы не было кучи мелких коммитов.
Наконец, в-третьих, не надо постоянно подмерждивать мастер, если это не требуется. Это усложняет историю ветки и создает лишние коммиты. Опять-таки, ты можешь найти рекомендации подмерждивать мастер регулярно, и во многих случаях это разумно, но надо всегда понимать, зачем ты это делаешь. Обычно это делают, чтобы твоя ветка не рассинхронизовалась с мастером, но даже на крупных промышленных проектах даже неделя отставания нередо не является существенной вещью. А уж на алгопроге, где коммиты раз в пару недель, это вообще незачем.